### ISSUE TITLE
[FEATURE] Make the extension work 

### ISSUE THREAD

**Issue by fstegmeyer** [netzpepper/npt3less#1]
![image](https://cloud.githubusercontent.com/assets/8909868/8725293/b38f9b90-2bd3-11e5-9942-2017965ecf03.png)

**Comment by theinrichs** [comment]
Bist du bescheuert? Siehst du hier n Release?!

**Comment by fstegmeyer** [comment]
Ich kann mich dran erinnern das du mich mal umhauen wolltest, weil ich eine Debug-Ausgabe in einem Commit hatte...

**Comment by theinrichs** [comment]
Und dann machst du einen Feature-Request im Bugtracker, einer Extension ohne Releases auf. 

Sehr gut.
